package com.example.student_management_system.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class UserTest {

    @Test
    void testUserLombok() {
        // Create a new user object
        User user = new User();

        // These setters are generated by Lombok!
        user.setId(10L);
        user.setUsername("mehedihasan");
        user.setPassword("password123");
        user.setRole("ROLE_STUDENT");

        // These getters are also generated by Lombok!
        assertEquals(10L, user.getId());
        assertEquals("mehedihasan", user.getUsername());
        assertEquals("ROLE_STUDENT", user.getRole());
    }
}